spring.application.name=api-gateway
server.port=9000


spring.cloud.gateway.routes[0].id=MALIBURGER
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/maliburger/**


spring.cloud.gateway.routes[1].id=ms-inventario
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/inventario/**


spring.cloud.gateway.routes[2].id=ms-carrito
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/carrito/**


spring.cloud.gateway.routes[3].id=ms-venta
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/venta/**

spring.datasource.hikari.maximum-pool-size=2

spring.datasource.hikari.minimum-idle=1

spring.datasource.hikari.connection-timeout=20000

spring.datasource.hikari.idle-timeout=30000