server.port=9000

spring.application.name=api-gateway

# --- 0. RUTA DEL CATÁLOGO ---
spring.cloud.gateway.routes[0].id=catalogo-route
spring.cloud.gateway.routes[0].uri=lb://MALIBURGER
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/maliburger/**

# --- 1. RUTA DEL CARRITO ---
spring.cloud.gateway.routes[1].id=carrito-route
spring.cloud.gateway.routes[1].uri=lb://MS-CARRITO
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/carrito/**

# --- 2. RUTA DE VENTAS ---
spring.cloud.gateway.routes[2].id=venta-route
spring.cloud.gateway.routes[2].uri=lb://MS-VENTA
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/venta/**

# --- 3. RUTA DEL INVENTARIO ---
spring.cloud.gateway.routes[3].id=inventario-route
spring.cloud.gateway.routes[3].uri=lb://MS-INVENTARIO
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/inventario/**

# --- 4. CONFIGURACIÓN DE SEGURIDAD ---
spring.cloud.gateway.routes[4].id=ms-seguridad-route
spring.cloud.gateway.routes[4].uri=lb://MSSECURITY
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/auth/**

# --- CONFIGURACIÓN DE EUREKA ---
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/


# --- CÁMARAS DE SEGURIDAD ---
logging.level.org.springframework.cloud.gateway=TRACE

spring.cloud.gateway.default-filters[0]=PreserveHostHeader

